using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;
using SixLabors.ImageSharp;
using System.IO;
using System.Numerics;
using System.Threading.Tasks;

namespace Content.Client._CorvaxGoob.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class ImageUi : DefaultWindow
{
    [Dependency] private readonly IResourceManager _resourceManager = default!;

    private static readonly ResPath BaseScreenshotPath = new("/Screenshots");

    private byte[]? _image;
    public ImageUi()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetImage(byte[] imageData)
    {
        try
        {
            MemoryStream stream = new MemoryStream(imageData);
            ImageDislay.Texture = Texture.LoadFromPNGStream(stream);
            _image = imageData;
        }
        catch { }
    }

    public async void SaveImage(string fileName)
    {
        if (!_resourceManager.UserData.IsDir(BaseScreenshotPath))
            _resourceManager.UserData.CreateDir(BaseScreenshotPath);

        await using var file = _resourceManager.UserData.Open(BaseScreenshotPath / $"{fileName}.png", FileMode.CreateNew, FileAccess.Write, FileShare.None);
        await file.WriteAsync(_image);
    }

    public void SetScale(Vector2 scale)
    {
        if (ImageDislay.Texture is null)
            return;

        this.SetSize = new(ImageDislay.Texture.Width * scale.X, ImageDislay.Texture.Height * scale.Y);
    }
}
