using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxGoob.BSA;

[GenerateTypedNameReferences]
public sealed partial class BSAControlBoxBuildWindow : FancyWindow
{
    public BSAControlBoxBuildWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
